name: kobi
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.5
  http: ^1.2.1
  intl: ^0.19.0
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.0
  smooth_page_indicator: ^1.1.0
  flutter_easyloading: ^3.0.5
  fl_chart: 0.66.1
  shimmer: ^3.0.0
  page_transition: ^2.1.0
  equatable: ^2.0.7
  flutter_staggered_animations: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: null
  flutter_gen: ^5.1.0+1
  flutter_gen_runner: null
  test: null


flutter_gen:
  integrations:
    flutter_svg: true
    flutter_localizations: true

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/json/
    - assets/image/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf